from typing import Any

PROVIDER_CATALOG: list[dict[str, Any]] = [
    {
        "type": "mock",
        "display_name": "Mock",
        "default_base_url": "mock://local",
        "auth_methods": ["anonymous"],
        "protocols": ["chat", "messages", "models"],
        "free_tier": True,
        "quota_query": False,
        "status": "implemented",
    },
    {
        "type": "openai",
        "display_name": "OpenAI",
        "default_base_url": "https://api.openai.com/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "responses", "models"],
        "free_tier": False,
        "quota_query": False,
        "status": "implemented",
    },
    {
        "type": "anthropic",
        "display_name": "Anthropic",
        "default_base_url": "https://api.anthropic.com/v1",
        "auth_methods": ["api_key"],
        "protocols": ["messages", "models"],
        "free_tier": False,
        "quota_query": False,
        "status": "implemented",
    },
    {
        "type": "gemini",
        "display_name": "Google Gemini",
        "default_base_url": "https://generativelanguage.googleapis.com/v1beta",
        "auth_methods": ["api_key", "oauth"],
        "protocols": ["chat", "models", "gemini_v1beta"],
        "free_tier": True,
        "quota_query": True,
        "status": "implemented",
    },
    {
        "type": "compatible",
        "display_name": "OpenAI Compatible",
        "default_base_url": "http://127.0.0.1:3000/v1",
        "auth_methods": ["api_key", "anonymous"],
        "protocols": ["chat", "models"],
        "free_tier": False,
        "quota_query": False,
        "status": "implemented",
    },
    {
        "type": "azure-openai",
        "display_name": "Azure OpenAI",
        "default_base_url": "https://<resource>.openai.azure.com",
        "auth_methods": ["api_key", "oauth"],
        "protocols": ["chat", "responses", "embeddings", "images", "audio"],
        "free_tier": False,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "vertex-ai",
        "display_name": "Google Vertex AI",
        "default_base_url": "https://<region>-aiplatform.googleapis.com",
        "auth_methods": ["oauth", "service_account"],
        "protocols": ["chat", "embeddings", "images", "gemini_v1beta"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "bedrock",
        "display_name": "AWS Bedrock",
        "default_base_url": "https://bedrock-runtime.<region>.amazonaws.com",
        "auth_methods": ["aws_credentials"],
        "protocols": ["chat", "messages", "embeddings", "images"],
        "free_tier": False,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "openrouter",
        "display_name": "OpenRouter",
        "default_base_url": "https://openrouter.ai/api/v1",
        "auth_methods": ["api_key", "oauth"],
        "protocols": ["chat", "models", "embeddings"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "xai",
        "display_name": "xAI",
        "default_base_url": "https://api.x.ai/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "images"],
        "free_tier": False,
        "quota_query": False,
        "status": "planned",
    },
    {
        "type": "mistral",
        "display_name": "Mistral AI",
        "default_base_url": "https://api.mistral.ai/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "embeddings", "moderations"],
        "free_tier": True,
        "quota_query": False,
        "status": "planned",
    },
    {
        "type": "cohere",
        "display_name": "Cohere",
        "default_base_url": "https://api.cohere.com/v2",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "embeddings", "rerank"],
        "free_tier": True,
        "quota_query": False,
        "status": "planned",
    },
    {
        "type": "deepseek",
        "display_name": "DeepSeek",
        "default_base_url": "https://api.deepseek.com/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models"],
        "free_tier": False,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "groq",
        "display_name": "Groq",
        "default_base_url": "https://api.groq.com/openai/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "audio"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "together",
        "display_name": "Together AI",
        "default_base_url": "https://api.together.xyz/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "embeddings", "images"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "fireworks",
        "display_name": "Fireworks AI",
        "default_base_url": "https://api.fireworks.ai/inference/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "embeddings"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "siliconflow",
        "display_name": "SiliconFlow",
        "default_base_url": "https://api.siliconflow.cn/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "embeddings", "images", "audio", "rerank"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "dashscope",
        "display_name": "Alibaba DashScope / Qwen",
        "default_base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "embeddings", "images", "audio"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "zhipu",
        "display_name": "Zhipu / GLM",
        "default_base_url": "https://open.bigmodel.cn/api/paas/v4",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "embeddings", "images", "video"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "moonshot",
        "display_name": "Moonshot / Kimi",
        "default_base_url": "https://api.moonshot.cn/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "files"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "volcengine",
        "display_name": "Volcengine / Doubao",
        "default_base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "embeddings", "images", "video"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
    {
        "type": "minimax",
        "display_name": "MiniMax",
        "default_base_url": "https://api.minimax.chat/v1",
        "auth_methods": ["api_key"],
        "protocols": ["chat", "models", "audio", "video", "music"],
        "free_tier": True,
        "quota_query": True,
        "status": "planned",
    },
]


def list_provider_catalog() -> list[dict[str, Any]]:
    return [dict(item) for item in PROVIDER_CATALOG]


def get_provider_catalog_item(provider_type: str) -> dict[str, Any] | None:
    return next((dict(item) for item in PROVIDER_CATALOG if item["type"] == provider_type), None)
